apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafanadata
  namespace: pgsql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
