apiVersion: v1
data:
  grafana.ini: |
    [users]
    allow_sign_up = false
    auto_assign_org = false

    [auth.proxy]
    enabled = true
    header_name = X-WEBAUTH-USER
    header_property = username
    auto_sign_up = false

    [server]
    root_url = /grafana
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: orc8r
    meta.helm.sh/release-namespace: pmn
  creationTimestamp: "2024-01-05T10:33:55Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: grafana-config-file
  namespace: pgsql
  resourceVersion: "54692311"
  uid: 36cdac80-07fb-4347-8d02-7fee3635fa11