apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: aws-efs
    volume.kubernetes.io/storage-provisioner: aws-efs
  creationTimestamp: "2023-06-15T11:23:22Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: grafanadatasources
  namespace: pmn
  resourceVersion: "20176"
  uid: 77d9137b-a25d-4989-a63e-15e0200a8cbe
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100M
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: pvc-77d9137b-a25d-4989-a63e-15e0200a8cbe
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100M
  phase: Bound