apiVersion: v1
data:
  alertmanager.yml: |
    route:
      receiver: null_receiver
      group_by:
        - alertname
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
    receivers:
      - name: null_receiver
  internal_alert_rules.yml: |
    groups:
      - name: internal_alerting_rules
        rules:
          - alert: target_down
            expr: up == 0
            labels:
              severity: major
              network_id: internal
            annotations:
              summary: "Instance {{ $labels.instance }} - target is down"
              description: "{{ $labels.instance }} is down."
kind: ConfigMap
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "0"
  creationTimestamp: "2024-12-23T11:01:54Z"
  labels:
    app.kubernetes.io/instance: orc8r
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: metrics
    app.kubernetes.io/version: "1.0"
    helm.sh/chart: metrics-1.4.24
  name: orc8r-metrics-defaultconfig
  namespace: pmn
  resourceVersion: "156665743"
  uid: e70c05f0-2e19-481a-8cc4-6a88a1e45c3c