apiVersion: batch/v1
kind: Job
metadata:
  name: orc8r-metrics-storeconfig
  namespace: pmn
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: orc8r-metrics
spec:
  template:
    metadata:
      name: orc8r-metrics-storeconfig
      labels:
        app: orc8r-metrics
    spec:
      restartPolicy: OnFailure
      containers:
        - name: storeconfig
          image: alpine:latest
          command:
            - /bin/sh
            - -c
            - |
              apk update && apk add --no-cache coreutils
              cp -n /mnt/defaults/alertmanager.yml /mnt/configs/ | true
              mkdir -p /mnt/configs/alert_rules && chmod +x /mnt/configs/alert_rules
              cp -n /mnt/defaults/*rules.yml /mnt/configs/alert_rules/ | true
          volumeMounts:
            - name: defaults
              mountPath: /mnt/defaults
            - name: configs
              mountPath: /mnt/configs
      volumes:
        - name: defaults
          configMap:
            name: orc8r-metrics-defaultconfig
        - name: configs
          persistentVolumeClaim:
            claimName: promcfg
