apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: pmn
  labels: # Move labels directly under metadata
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: "pmndev" # Database name
        - name: POSTGRES_USER
          value: "pmn" # Username
        - name: POSTGRES_PASSWORD
          value: "juniperprod1234" # Password
        ports:
        - containerPort: 5432


