apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: pmn
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - port: 5432               # Port that the service will expose
      targetPort: 5432         # Port on the container
      nodePort: 30000          # NodePort range (default: 30000-32767)
