{{- include "orc8rlib.deployment" (list . "notifier.deployment") -}}
{{- define "notifier.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orc8r-notifier
  labels:
    app.kubernetes.io/component: notifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: notifier
  template:
    metadata:
      labels:
        app.kubernetes.io/component: notifier
    spec:
      containers:
      - 
{{ include "orc8rlib.container" (list . "notifier.container")}}
{{- end -}}
{{- define "notifier.container" -}}
name: notifier
image: {{ .Values.notifier.image.repository }}:{{ .Values.notifier.image.tag }}
args: 
  - sh 
  - -c
  - java -jar Orc8rNotificationService-1.0-SNAPSHOT.jar  "{{ .Values.notifier.publisherPort }}" "{{ .Values.global.subscriberPort }}"
env:
- name: PUBLISHER_PORT
  value: "{{ .Values.notifier.publisherPort }}"
- name: SUBSCRIBER_PORT
  value: "{{ .Values.global.subscriberPort }}"
- name: NOTIF_CERT_CA
  value: "{{ .Values.notifier.notifierCACert }}"
- name: NOTIF_SERVER_CERT
  value: "{{ .Values.notifier.notifierServerCert }}"
- name: NOTIF_SERVER_KEY
  value: "{{ .Values.notifier.notifierServerKey }}"
- name: NOTIF_SUBSCRIBER
  value: "notifier-internal"
- name: NOTIF_PUBLISHER
  value: "notifier-internal"
livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 30
  tcpSocket:
    port: {{ .Values.notifier.publisherPort }}
readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 30
  tcpSocket:
    port: {{.Values.notifier.publisherPort }}
ports:
- name: notifier
  containerPort: {{ .Values.global.subscriberPort }}
{{- end -}}
