apiVersion: v1
kind: Secret
metadata:
  name: pmn-envdir
  namespace: pmn
type: Opaque
data:
  CONTROLLER_SERVICES: Q09ORklHVVJBVE9SLFNUQVRFLFNUUkVBTUVSLFBPTElDWURCLE1FVFJJQ1NELENFUlRJRklFUixCT09UU1RSQVBQRVIsQUNDRVNTRCxPQlNJRElBTixESVNQQVRDSEVSLERJUkVDVE9SWUQsQ1RSQUNFRA==
