{{- if .Values.prometheus.nginx.create }}
{{- $serviceName := print .Release.Name "-prometheus-nginx-proxy" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: prometheus-nginx
{{ include "metrics.labels" . | indent 4 }}
  name: {{ $serviceName }} 
spec:
  replicas: {{ .Values.prometheus.nginx.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: prometheus-nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: prometheus-nginx
    spec:
      containers:
      - image: "{{ .Values.prometheus.nginx.image.repository }}:{{ .Values.prometheus.nginx.image.tag }}"
        imagePullPolicy: {{ .Values.prometheus.nginx.image.pullPolicy }}
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 443
        name: prometheus-nginx
        ports:
        - containerPort: 443
          protocol: TCP
        readinessProbe:
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 443
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/nginx_prometheus_ssl.conf
          name: prometheus-nginx-proxy
          subPath: nginx_prometheus_ssl.conf
        - mountPath: /etc/nginx/conf.d/{{ .Values.prometheus.nginx.spec.ssl_cert_name }}
          name: prometheus-certs
          readOnly: true
          subPath: {{ .Values.prometheus.nginx.spec.ssl_cert_name }}
        - mountPath: /etc/nginx/conf.d/{{ .Values.prometheus.nginx.spec.ssl_key_name }}
          name: prometheus-certs
          subPath: {{ .Values.prometheus.nginx.spec.ssl_key_name }}
        - mountPath: /etc/nginx/conf.d/{{ .Values.prometheus.nginx.spec.ssl_certificate }}
          name: prometheus-certs
          readOnly: true
          subPath: {{ .Values.prometheus.nginx.spec.ssl_certificate }}
      volumes:
      - configMap:
          defaultMode: 365
          name: prometheus-nginx-proxy
        name: prometheus-nginx-proxy
      - name: prometheus-certs
        secret:
          defaultMode: 292
          secretName: {{ required "secretName must be provided" .Values.prometheus.nginx.secretName }}
{{- end }}
