apiVersion: pmnsystems.pmnsystem.com/v1alpha1
kind: Pmnsystem
metadata:
  labels:
    app.kubernetes.io/name: pmnsystem
    app.kubernetes.io/instance: pmnsystem-sample
    app.kubernetes.io/part-of: pmn-operator-two
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: pmn-operator-two
  name: pmnsystem-sample
spec:
  # TODO(user): Add fields here
  envVariablesPrometheusKafka:
    - name: "KAFKA_BROKER_LIST"
      value: "a7eda74b9c8a841b2935e41ee307e0df-1871632677.us-west-2.elb.amazonaws.com:9094"
    - name: "KAFKA_TOPIC"
      value: "metrics"
    - name: "KAFKA_SECURITY_PROTOCOL"
      value: "sasl_ssl"
    - name: "KAFKA_SASL_MECHANISM"
      value: "PLAIN"
    - name: "KAFKA_SASL_USERNAME"
      value: "admin"
    - name: "KAFKA_SASL_PASSWORD"
      value: "admin-secret"
    - name: "KAFKA_COMPRESSION"
      value: ""
    - name: "KAFKA_BATCH_NUM_MESSAGES"
      value: ""
    - name: "SERIALIZATION_FORMAT"
      value: ""
    - name: "PORT"
      value: "8080"
    - name: "LOG_LEVEL"
      value: ""
    - name: "GIN_MODE"
      value: ""
    - name: "KAFKA_SSL_CLIENT_CERT_FILE"
      value: "/client_cert/adapter-client.crt"
    - name: "KAFKA_SSL_CLIENT_KEY_FILE"
      value: "/client_cert/adapter-client.key"
    - name: "KAFKA_SSL_CA_CERT_FILE"
      value: "/client_cert/adapter-ca.crt"
  envVariablesNMSMagmaLte:
    - name: "API_CERT_FILENAME"
      value: "/run/secrets/admin_operator.pem"
    - name: "API_PRIVATE_KEY_FILENAME"
      value: "/run/secrets/admin_operator.key.pem"
    - name: "API_HOST"
      value: "api.operator.wavelabs.int"
    - name: "HOST"
      value: "0.0.0.0"
    - name: "PORT"
      value: "8081"
    - name: "MYSQL_DB"
      value: "pmndev"
    - name: "MYSQL_HOST"
      value: "postgres.pgsql.svc.cluster.local"
    - name: "MYSQL_PORT"
      value: "5432"
    - name: "MYSQL_DIALECT"
      value: "postgres"
    - name: "USER_GRAFANA_ADDRESS"
      value: "orc8r-user-grafana:3000"
  envVariablesNMSMagmaLteDevEnv:
    - name: API_CERT_FILENAME
      value: /run/secrets/admin_operator.pem      
    - name: API_PRIVATE_KEY_FILENAME
      value: /run/secrets/admin_operator.key.pem 
    - name: API_HOST
      value: api.operator.wavelabs.int
    - name: HOST
      value: "0.0.0.0"
    - name: PORT
      value: "8081"
    - name: MYSQL_DB
      value: postgres
    - name: MYSQL_HOST
      value: postgres.pgsql.svc.cluster.local
    - name: MYSQL_PORT
      value: "5432"
    - name: MYSQL_DIALECT
      value: postgres
    - name: USER_GRAFANA_ADDRESS
      value: orc8r-user-grafana:3000
  envVariablesOrc8rNotifier:
    - name: "PUBLISHER_PORT"
      value: "5442"
    - name: "SUBSCRIBER_PORT"
      value: "443"
    - name: "NOTIF_CERT_CA"
      value: "notifier-ca.crt"
    - name: "NOTIF_SERVER_CERT"
      value: "notifier.crt"
    - name: "NOTIF_SERVER_KEY"
      value: "notifier.key"
    - name: "NOTIF_SUBSCRIBER"
      value: "notifier-internal"
    - name: "NOTIF_PUBLISHER"
      value: "notifier-internal"
  envVariablesOrc8rNginx:
    - name: "PROXY_BACKENDS"
      value: "postgres.pgsql.svc.cluster.local"
    - name: "CONTROLLER_HOSTNAME"
      value: "controller.operator.wavelabs.int"
    - name: "RESOLVER"
      value: "coredns.kube-system.svc.cluster.local valid=10s"
    - name: "SERVICE_REGISTRY_MODE"
      value: "k8s "
    - name: "SSL_CERTIFICATE"
      value: "/var/opt/magma/certs/controller.crt"
    - name: "SSL_CERTIFICATE_KEY"
      value: "/var/opt/magma/certs/controller.key"
    - name: "SSL_CLIENT_CERTIFICATE"
      value: "/var/opt/magma/certs/certifier.pem"
  envVariablesDirectoryD:
    - name: "SQL_DRIVER"
      value: "postgres"
    - name: "SQL_DIALECT"
      value: "psql"
    - name: "SERVICE_REGISTRY_MODE"
      value: "k8s"
    - name: "HELM_RELEASE_NAME"
      value: "orc8r"
    - name: "SERVICE_REGISTRY_NAMESPACE"
      value: "pmn"
    - name: "HELM_VERSION_TAG"
      value: "1.8.0"
    - name: "VERSION_TAG"
      value: "1.8.0-6c4579b5"
    - name: "ORC8R_DOMAIN_NAME"
      value: "magma.test"
    - name: "PUBLISHER_PORT"
      value: "5442"
    - name: "SUBSCRIBER_PORT"
      value: "443"
    - name: "NOTIF_PUBLISHER"
      value: "notifier-internal"
    - name: "NOTIF_SUBSCRIBER"
      value: "notifier-internal"
  envVariables:
    - name: "SQL_DRIVER"
      value: "postgres"
    - name: "SQL_DIALECT"
      value: "psql"
    - name: "SERVICE_REGISTRY_MODE"
      value: "k8s"
    - name: "HELM_RELEASE_NAME"
      value: "orc8r"
    - name: "SERVICE_REGISTRY_NAMESPACE"
      value: "pmn"
    - name: "HELM_VERSION_TAG"
      value: "1.8.0"
    - name: "VERSION_TAG"
      value: "1.8.0-6c4579b5"
    - name: "ORC8R_DOMAIN_NAME"
      value: "magma.test"
    - name: "PUBLISHER_PORT"
      value: "5442"
    - name: "SUBSCRIBER_PORT"
      value: "443"
    - name: "NOTIF_PUBLISHER"
      value: "notifier-internal"
    - name: "NOTIF_SUBSCRIBER"
      value: "notifier-internal"
    - name: "NOTIF_CERT_CA"
      value: "notifier-ca.crt"
    - name: "NOTIF_SERVER_CERT"
      value: "notifier.crt"
    - name: "NOTIF_SERVER_KEY"
      value: "notifier.key"
  replicaCount: 1
  pullPolicy: IfNotPresent
  nameSpace: "pgsql"
  notifierImage: "815281572631.dkr.ecr.us-west-2.amazonaws.com/pmn/dev/notifier:1.8.0-a914c772"
  nginxImage: "815281572631.dkr.ecr.us-west-2.amazonaws.com/pmn/dev/nginx:1.8.0-a914c772"
  imagePullSecrets: "artifactory"
  imageMagmaLte: "815281572631.dkr.ecr.us-west-2.amazonaws.com/pmn/dev/magmalte:1.8.0-a914c772"
  devEnvironment: true
  cloudEnvironment: false
  persistentForStatefulSet:
    pvcClaimName: "abc"
    storageClassName: "nfs"
  persistent:
    pvcClaimName: "abc"
    storageClassName: "nfs"
  image:
    repository: "815281572631.dkr.ecr.us-west-2.amazonaws.com/pmn/dev/controller"
    tag: "1.8.0-6c4579b5"