apiVersion: pmnsystems.pmnsystem.com/v1alpha1
kind: Pmnsystem
metadata:
  labels:
    app.kubernetes.io/name: pmnsystem
    app.kubernetes.io/instance: pmnsystem-sample
    app.kubernetes.io/part-of: pmn-operator-two
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: pmn-operator-two
  name: pmnsystem-sample
spec:
  # TODO(user): Add fields here
  replicaCount: 1
  pullPolicy: IfNotPresent
  nameSpace: "pmn"
  persistent:
    pvcClaimName: "abc"
    storageClassName: "standard"
  image:
    repository: "815281572631.dkr.ecr.us-west-2.amazonaws.com/pmn/dev/controller"
    tag: "1.8.0-6c4579b5"
