apiVersion: pmnsystems.pmnsystem.com/v1alpha1
kind: Pmnsystem
metadata:
  labels:
    app.kubernetes.io/name: pmnsystem
    app.kubernetes.io/instance: pmnsystem-sample
    app.kubernetes.io/part-of: pmn-operator-two
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: pmn-operator-two
  name: pmnsystem-sample
spec:
  # TODO(user): Add fields here
  imagePullSecrets: "artifactory"
  envVariables:
    - name: "SQL_DRIVER"
      value: "postgres"
    - name: "SQL_DIALECT"
      value: "psql"
    - name: "SERVICE_REGISTRY_MODE"
      value: "k8s"
    - name: "HELM_RELEASE_NAME"
      value: "orc8r"
    - name: "SERVICE_REGISTRY_NAMESPACE"
      value: "pmn"
    - name: "HELM_VERSION_TAG"
      value: "1.8.0"
    - name: "VERSION_TAG"
      value: "1.8.0-6c4579b5"
    - name: "ORC8R_DOMAIN_NAME"
      value: "magma.test"
    - name: "PUBLISHER_PORT"
      value: "5442"
    - name: "SUBSCRIBER_PORT"
      value: "443"
    - name: "NOTIF_PUBLISHER"
      value: "notifier-internal"
    - name: "NOTIF_SUBSCRIBER"
      value: "notifier-internal"
    - name: "NOTIF_CERT_CA"
      value: "notifier-ca.crt"
    - name: "NOTIF_SERVER_CERT"
      value: "notifier.crt"
    - name: "NOTIF_SERVER_KEY"
      value: "notifier.key"
  replicaCount: 1
  pullPolicy: IfNotPresent
  nameSpace: "pmn"
  persistent:
    pvcClaimName: "abc"
    storageClassName: "standard"
  image:
    repository: "815281572631.dkr.ecr.us-west-2.amazonaws.com/pmn/dev/controller"
    tag: "1.8.0-6c4579b5"
