//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertManager) DeepCopyInto(out *AlertManager) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.ImageAlertmanager = in.ImageAlertmanager
	in.ServiceSpec.DeepCopyInto(&out.ServiceSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertManager.
func (in *AlertManager) DeepCopy() *AlertManager {
	if in == nil {
		return nil
	}
	out := new(AlertManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertmanagerConfigurer) DeepCopyInto(out *AlertmanagerConfigurer) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.ImageAlertmanagerConfigurer = in.ImageAlertmanagerConfigurer
	in.ServiceSpec.DeepCopyInto(&out.ServiceSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertmanagerConfigurer.
func (in *AlertmanagerConfigurer) DeepCopy() *AlertmanagerConfigurer {
	if in == nil {
		return nil
	}
	out := new(AlertmanagerConfigurer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentVariables) DeepCopyInto(out *EnvironmentVariables) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentVariables.
func (in *EnvironmentVariables) DeepCopy() *EnvironmentVariables {
	if in == nil {
		return nil
	}
	out := new(EnvironmentVariables)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentVariablesDirectoryD) DeepCopyInto(out *EnvironmentVariablesDirectoryD) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentVariablesDirectoryD.
func (in *EnvironmentVariablesDirectoryD) DeepCopy() *EnvironmentVariablesDirectoryD {
	if in == nil {
		return nil
	}
	out := new(EnvironmentVariablesDirectoryD)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentVariablesNMSMagmaLte) DeepCopyInto(out *EnvironmentVariablesNMSMagmaLte) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentVariablesNMSMagmaLte.
func (in *EnvironmentVariablesNMSMagmaLte) DeepCopy() *EnvironmentVariablesNMSMagmaLte {
	if in == nil {
		return nil
	}
	out := new(EnvironmentVariablesNMSMagmaLte)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentVariablesNMSMagmaLteDevEnv) DeepCopyInto(out *EnvironmentVariablesNMSMagmaLteDevEnv) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentVariablesNMSMagmaLteDevEnv.
func (in *EnvironmentVariablesNMSMagmaLteDevEnv) DeepCopy() *EnvironmentVariablesNMSMagmaLteDevEnv {
	if in == nil {
		return nil
	}
	out := new(EnvironmentVariablesNMSMagmaLteDevEnv)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentVariablesOrc8rNginx) DeepCopyInto(out *EnvironmentVariablesOrc8rNginx) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentVariablesOrc8rNginx.
func (in *EnvironmentVariablesOrc8rNginx) DeepCopy() *EnvironmentVariablesOrc8rNginx {
	if in == nil {
		return nil
	}
	out := new(EnvironmentVariablesOrc8rNginx)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentVariablesOrc8rNotifier) DeepCopyInto(out *EnvironmentVariablesOrc8rNotifier) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentVariablesOrc8rNotifier.
func (in *EnvironmentVariablesOrc8rNotifier) DeepCopy() *EnvironmentVariablesOrc8rNotifier {
	if in == nil {
		return nil
	}
	out := new(EnvironmentVariablesOrc8rNotifier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentVariablesPrometheusKafka) DeepCopyInto(out *EnvironmentVariablesPrometheusKafka) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentVariablesPrometheusKafka.
func (in *EnvironmentVariablesPrometheusKafka) DeepCopy() *EnvironmentVariablesPrometheusKafka {
	if in == nil {
		return nil
	}
	out := new(EnvironmentVariablesPrometheusKafka)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Image) DeepCopyInto(out *Image) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Image.
func (in *Image) DeepCopy() *Image {
	if in == nil {
		return nil
	}
	out := new(Image)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageAlertmanager) DeepCopyInto(out *ImageAlertmanager) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageAlertmanager.
func (in *ImageAlertmanager) DeepCopy() *ImageAlertmanager {
	if in == nil {
		return nil
	}
	out := new(ImageAlertmanager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageAlertmanagerConfigurer) DeepCopyInto(out *ImageAlertmanagerConfigurer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageAlertmanagerConfigurer.
func (in *ImageAlertmanagerConfigurer) DeepCopy() *ImageAlertmanagerConfigurer {
	if in == nil {
		return nil
	}
	out := new(ImageAlertmanagerConfigurer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageMagmaLte) DeepCopyInto(out *ImageMagmaLte) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageMagmaLte.
func (in *ImageMagmaLte) DeepCopy() *ImageMagmaLte {
	if in == nil {
		return nil
	}
	out := new(ImageMagmaLte)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageOrc8rNginx) DeepCopyInto(out *ImageOrc8rNginx) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageOrc8rNginx.
func (in *ImageOrc8rNginx) DeepCopy() *ImageOrc8rNginx {
	if in == nil {
		return nil
	}
	out := new(ImageOrc8rNginx)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageOrc8rNotifier) DeepCopyInto(out *ImageOrc8rNotifier) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageOrc8rNotifier.
func (in *ImageOrc8rNotifier) DeepCopy() *ImageOrc8rNotifier {
	if in == nil {
		return nil
	}
	out := new(ImageOrc8rNotifier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagePrometheusCache) DeepCopyInto(out *ImagePrometheusCache) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagePrometheusCache.
func (in *ImagePrometheusCache) DeepCopy() *ImagePrometheusCache {
	if in == nil {
		return nil
	}
	out := new(ImagePrometheusCache)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagePrometheusConfigurer) DeepCopyInto(out *ImagePrometheusConfigurer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagePrometheusConfigurer.
func (in *ImagePrometheusConfigurer) DeepCopy() *ImagePrometheusConfigurer {
	if in == nil {
		return nil
	}
	out := new(ImagePrometheusConfigurer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagePrometheusKafkaAdapter) DeepCopyInto(out *ImagePrometheusKafkaAdapter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagePrometheusKafkaAdapter.
func (in *ImagePrometheusKafkaAdapter) DeepCopy() *ImagePrometheusKafkaAdapter {
	if in == nil {
		return nil
	}
	out := new(ImagePrometheusKafkaAdapter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagePrometheusNginxProxy) DeepCopyInto(out *ImagePrometheusNginxProxy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagePrometheusNginxProxy.
func (in *ImagePrometheusNginxProxy) DeepCopy() *ImagePrometheusNginxProxy {
	if in == nil {
		return nil
	}
	out := new(ImagePrometheusNginxProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageUserGrafana) DeepCopyInto(out *ImageUserGrafana) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageUserGrafana.
func (in *ImageUserGrafana) DeepCopy() *ImageUserGrafana {
	if in == nil {
		return nil
	}
	out := new(ImageUserGrafana)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Metrics) DeepCopyInto(out *Metrics) {
	*out = *in
	out.Volumes = in.Volumes
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Metrics.
func (in *Metrics) DeepCopy() *Metrics {
	if in == nil {
		return nil
	}
	out := new(Metrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Nginx) DeepCopyInto(out *Nginx) {
	*out = *in
	in.ServiceOrc8rSpec.DeepCopyInto(&out.ServiceOrc8rSpec)
	out.ImagePrometheusNginxProxy = in.ImagePrometheusNginxProxy
	in.VolumeMountPath.DeepCopyInto(&out.VolumeMountPath)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Nginx.
func (in *Nginx) DeepCopy() *Nginx {
	if in == nil {
		return nil
	}
	out := new(Nginx)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NmsMagmaLte) DeepCopyInto(out *NmsMagmaLte) {
	*out = *in
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.ImageMagmaLte = in.ImageMagmaLte
	in.VolumeMountNmsMagmaLte.DeepCopyInto(&out.VolumeMountNmsMagmaLte)
	in.VolumesNmsMagmaLte.DeepCopyInto(&out.VolumesNmsMagmaLte)
	in.ServiceSpec.DeepCopyInto(&out.ServiceSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NmsMagmaLte.
func (in *NmsMagmaLte) DeepCopy() *NmsMagmaLte {
	if in == nil {
		return nil
	}
	out := new(NmsMagmaLte)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Orc8rNginxDeployment) DeepCopyInto(out *Orc8rNginxDeployment) {
	*out = *in
	out.ImageOrc8rNginx = in.ImageOrc8rNginx
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.VolumesOrc8rNginx.DeepCopyInto(&out.VolumesOrc8rNginx)
	in.PortOrc8rNginx.DeepCopyInto(&out.PortOrc8rNginx)
	in.VolumesMountPathOrc8rNginx.DeepCopyInto(&out.VolumesMountPathOrc8rNginx)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Orc8rNginxDeployment.
func (in *Orc8rNginxDeployment) DeepCopy() *Orc8rNginxDeployment {
	if in == nil {
		return nil
	}
	out := new(Orc8rNginxDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Orc8rNotifier) DeepCopyInto(out *Orc8rNotifier) {
	*out = *in
	out.ImageOrc8rNotifier = in.ImageOrc8rNotifier
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.ServiceSpecOrc8rNotifier.DeepCopyInto(&out.ServiceSpecOrc8rNotifier)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Orc8rNotifier.
func (in *Orc8rNotifier) DeepCopy() *Orc8rNotifier {
	if in == nil {
		return nil
	}
	out := new(Orc8rNotifier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistenForStatefulSet) DeepCopyInto(out *PersistenForStatefulSet) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistenForStatefulSet.
func (in *PersistenForStatefulSet) DeepCopy() *PersistenForStatefulSet {
	if in == nil {
		return nil
	}
	out := new(PersistenForStatefulSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Persistent) DeepCopyInto(out *Persistent) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Persistent.
func (in *Persistent) DeepCopy() *Persistent {
	if in == nil {
		return nil
	}
	out := new(Persistent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Pmnsystem) DeepCopyInto(out *Pmnsystem) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Pmnsystem.
func (in *Pmnsystem) DeepCopy() *Pmnsystem {
	if in == nil {
		return nil
	}
	out := new(Pmnsystem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Pmnsystem) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PmnsystemList) DeepCopyInto(out *PmnsystemList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Pmnsystem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PmnsystemList.
func (in *PmnsystemList) DeepCopy() *PmnsystemList {
	if in == nil {
		return nil
	}
	out := new(PmnsystemList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PmnsystemList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PmnsystemSpec) DeepCopyInto(out *PmnsystemSpec) {
	*out = *in
	out.Persistent = in.Persistent
	out.PersistentForStatefulSet = in.PersistentForStatefulSet
	out.Image = in.Image
	if in.EnvVariables != nil {
		in, out := &in.EnvVariables, &out.EnvVariables
		*out = make([]EnvironmentVariables, len(*in))
		copy(*out, *in)
	}
	if in.EnvVariablesDirectoryD != nil {
		in, out := &in.EnvVariablesDirectoryD, &out.EnvVariablesDirectoryD
		*out = make([]EnvironmentVariablesDirectoryD, len(*in))
		copy(*out, *in)
	}
	if in.EnvVariablesOrc8rNginx != nil {
		in, out := &in.EnvVariablesOrc8rNginx, &out.EnvVariablesOrc8rNginx
		*out = make([]EnvironmentVariablesOrc8rNginx, len(*in))
		copy(*out, *in)
	}
	if in.EnvVariablesOrc8rNotifier != nil {
		in, out := &in.EnvVariablesOrc8rNotifier, &out.EnvVariablesOrc8rNotifier
		*out = make([]EnvironmentVariablesOrc8rNotifier, len(*in))
		copy(*out, *in)
	}
	if in.EnvVariablesNMSMagmaLte != nil {
		in, out := &in.EnvVariablesNMSMagmaLte, &out.EnvVariablesNMSMagmaLte
		*out = make([]EnvironmentVariablesNMSMagmaLte, len(*in))
		copy(*out, *in)
	}
	if in.EnvVariablesNMSMagmaLteDevEnv != nil {
		in, out := &in.EnvVariablesNMSMagmaLteDevEnv, &out.EnvVariablesNMSMagmaLteDevEnv
		*out = make([]EnvironmentVariablesNMSMagmaLteDevEnv, len(*in))
		copy(*out, *in)
	}
	if in.EnvVariablesPrometheusKafka != nil {
		in, out := &in.EnvVariablesPrometheusKafka, &out.EnvVariablesPrometheusKafka
		*out = make([]EnvironmentVariablesPrometheusKafka, len(*in))
		copy(*out, *in)
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]SecretConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.AlertmanagerConfigurer.DeepCopyInto(&out.AlertmanagerConfigurer)
	out.Metrics = in.Metrics
	out.Prometheus = in.Prometheus
	in.AlertManager.DeepCopyInto(&out.AlertManager)
	in.UserGrafana.DeepCopyInto(&out.UserGrafana)
	in.PrometheusNginxProxy.DeepCopyInto(&out.PrometheusNginxProxy)
	in.PrometheusKafkaAdapter.DeepCopyInto(&out.PrometheusKafkaAdapter)
	in.PrometheusConfigurer.DeepCopyInto(&out.PrometheusConfigurer)
	in.PrometheusCache.DeepCopyInto(&out.PrometheusCache)
	in.NmsMagmaLte.DeepCopyInto(&out.NmsMagmaLte)
	in.Orc8rNotifier.DeepCopyInto(&out.Orc8rNotifier)
	in.Orc8rNginxDeployment.DeepCopyInto(&out.Orc8rNginxDeployment)
	if in.LinesToReplace != nil {
		in, out := &in.LinesToReplace, &out.LinesToReplace
		*out = make(map[string]map[string]string, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.NewFileNames != nil {
		in, out := &in.NewFileNames, &out.NewFileNames
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PmnsystemSpec.
func (in *PmnsystemSpec) DeepCopy() *PmnsystemSpec {
	if in == nil {
		return nil
	}
	out := new(PmnsystemSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PmnsystemStatus) DeepCopyInto(out *PmnsystemStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PmnsystemStatus.
func (in *PmnsystemStatus) DeepCopy() *PmnsystemStatus {
	if in == nil {
		return nil
	}
	out := new(PmnsystemStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortOrc8rNginx) DeepCopyInto(out *PortOrc8rNginx) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortOrc8rNginx.
func (in *PortOrc8rNginx) DeepCopy() *PortOrc8rNginx {
	if in == nil {
		return nil
	}
	out := new(PortOrc8rNginx)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortOrc8rSpec) DeepCopyInto(out *PortOrc8rSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortOrc8rSpec.
func (in *PortOrc8rSpec) DeepCopy() *PortOrc8rSpec {
	if in == nil {
		return nil
	}
	out := new(PortOrc8rSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortSpec) DeepCopyInto(out *PortSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortSpec.
func (in *PortSpec) DeepCopy() *PortSpec {
	if in == nil {
		return nil
	}
	out := new(PortSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortSpecOrc8rNotifier) DeepCopyInto(out *PortSpecOrc8rNotifier) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortSpecOrc8rNotifier.
func (in *PortSpecOrc8rNotifier) DeepCopy() *PortSpecOrc8rNotifier {
	if in == nil {
		return nil
	}
	out := new(PortSpecOrc8rNotifier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortSpecPrometheusKafkaAdapter) DeepCopyInto(out *PortSpecPrometheusKafkaAdapter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortSpecPrometheusKafkaAdapter.
func (in *PortSpecPrometheusKafkaAdapter) DeepCopy() *PortSpecPrometheusKafkaAdapter {
	if in == nil {
		return nil
	}
	out := new(PortSpecPrometheusKafkaAdapter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Prometheus) DeepCopyInto(out *Prometheus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Prometheus.
func (in *Prometheus) DeepCopy() *Prometheus {
	if in == nil {
		return nil
	}
	out := new(Prometheus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusCache) DeepCopyInto(out *PrometheusCache) {
	*out = *in
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.ImagePrometheusCache = in.ImagePrometheusCache
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.ServiceSpec.DeepCopyInto(&out.ServiceSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusCache.
func (in *PrometheusCache) DeepCopy() *PrometheusCache {
	if in == nil {
		return nil
	}
	out := new(PrometheusCache)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusConfig) DeepCopyInto(out *PrometheusConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusConfig.
func (in *PrometheusConfig) DeepCopy() *PrometheusConfig {
	if in == nil {
		return nil
	}
	out := new(PrometheusConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusConfigurer) DeepCopyInto(out *PrometheusConfigurer) {
	*out = *in
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.ImagePrometheusConfigurer = in.ImagePrometheusConfigurer
	out.Volume = in.Volume
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.ServiceSpec.DeepCopyInto(&out.ServiceSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusConfigurer.
func (in *PrometheusConfigurer) DeepCopy() *PrometheusConfigurer {
	if in == nil {
		return nil
	}
	out := new(PrometheusConfigurer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusKafkaAdapter) DeepCopyInto(out *PrometheusKafkaAdapter) {
	*out = *in
	out.ImagePrometheusKafkaAdapter = in.ImagePrometheusKafkaAdapter
	in.VolumeMountPathPrometheusKafkaAdapter.DeepCopyInto(&out.VolumeMountPathPrometheusKafkaAdapter)
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.ServiceSpecPrometheusKafkaAdapter.DeepCopyInto(&out.ServiceSpecPrometheusKafkaAdapter)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusKafkaAdapter.
func (in *PrometheusKafkaAdapter) DeepCopy() *PrometheusKafkaAdapter {
	if in == nil {
		return nil
	}
	out := new(PrometheusKafkaAdapter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusNginxProxy) DeepCopyInto(out *PrometheusNginxProxy) {
	*out = *in
	in.Nginx.DeepCopyInto(&out.Nginx)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusNginxProxy.
func (in *PrometheusNginxProxy) DeepCopy() *PrometheusNginxProxy {
	if in == nil {
		return nil
	}
	out := new(PrometheusNginxProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretConfig) DeepCopyInto(out *SecretConfig) {
	*out = *in
	if in.RequiredFiles != nil {
		in, out := &in.RequiredFiles, &out.RequiredFiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretConfig.
func (in *SecretConfig) DeepCopy() *SecretConfig {
	if in == nil {
		return nil
	}
	out := new(SecretConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceOrc8rSpec) DeepCopyInto(out *ServiceOrc8rSpec) {
	*out = *in
	if in.PortOrc8rSpec != nil {
		in, out := &in.PortOrc8rSpec, &out.PortOrc8rSpec
		*out = make([]PortOrc8rSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceOrc8rSpec.
func (in *ServiceOrc8rSpec) DeepCopy() *ServiceOrc8rSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceOrc8rSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpec) DeepCopyInto(out *ServiceSpec) {
	*out = *in
	if in.PortSpec != nil {
		in, out := &in.PortSpec, &out.PortSpec
		*out = make([]PortSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpec.
func (in *ServiceSpec) DeepCopy() *ServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpecOrc8rNotifier) DeepCopyInto(out *ServiceSpecOrc8rNotifier) {
	*out = *in
	if in.PortSpecOrc8rNotifier != nil {
		in, out := &in.PortSpecOrc8rNotifier, &out.PortSpecOrc8rNotifier
		*out = make([]PortSpecOrc8rNotifier, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpecOrc8rNotifier.
func (in *ServiceSpecOrc8rNotifier) DeepCopy() *ServiceSpecOrc8rNotifier {
	if in == nil {
		return nil
	}
	out := new(ServiceSpecOrc8rNotifier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpecPrometheusKafkaAdapter) DeepCopyInto(out *ServiceSpecPrometheusKafkaAdapter) {
	*out = *in
	if in.PortSpecPrometheusKafkaAdapter != nil {
		in, out := &in.PortSpecPrometheusKafkaAdapter, &out.PortSpecPrometheusKafkaAdapter
		*out = make([]PortSpecPrometheusKafkaAdapter, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpecPrometheusKafkaAdapter.
func (in *ServiceSpecPrometheusKafkaAdapter) DeepCopy() *ServiceSpecPrometheusKafkaAdapter {
	if in == nil {
		return nil
	}
	out := new(ServiceSpecPrometheusKafkaAdapter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserGrafana) DeepCopyInto(out *UserGrafana) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.ImageUserGrafana = in.ImageUserGrafana
	if in.VolumesUserGrafana != nil {
		in, out := &in.VolumesUserGrafana, &out.VolumesUserGrafana
		*out = make([]VolumesUserGrafana, len(*in))
		copy(*out, *in)
	}
	in.ServiceSpec.DeepCopyInto(&out.ServiceSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserGrafana.
func (in *UserGrafana) DeepCopy() *UserGrafana {
	if in == nil {
		return nil
	}
	out := new(UserGrafana)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Volume) DeepCopyInto(out *Volume) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Volume.
func (in *Volume) DeepCopy() *Volume {
	if in == nil {
		return nil
	}
	out := new(Volume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeMountNmsMagmaLte) DeepCopyInto(out *VolumeMountNmsMagmaLte) {
	*out = *in
	if in.VolumeMountPath != nil {
		in, out := &in.VolumeMountPath, &out.VolumeMountPath
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.VolumeSubPath != nil {
		in, out := &in.VolumeSubPath, &out.VolumeSubPath
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeMountNmsMagmaLte.
func (in *VolumeMountNmsMagmaLte) DeepCopy() *VolumeMountNmsMagmaLte {
	if in == nil {
		return nil
	}
	out := new(VolumeMountNmsMagmaLte)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeMountPath) DeepCopyInto(out *VolumeMountPath) {
	*out = *in
	if in.MountPath != nil {
		in, out := &in.MountPath, &out.MountPath
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SubPath != nil {
		in, out := &in.SubPath, &out.SubPath
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeMountPath.
func (in *VolumeMountPath) DeepCopy() *VolumeMountPath {
	if in == nil {
		return nil
	}
	out := new(VolumeMountPath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeMountPathPrometheusKafkaAdapter) DeepCopyInto(out *VolumeMountPathPrometheusKafkaAdapter) {
	*out = *in
	if in.MountPath != nil {
		in, out := &in.MountPath, &out.MountPath
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeMountPathPrometheusKafkaAdapter.
func (in *VolumeMountPathPrometheusKafkaAdapter) DeepCopy() *VolumeMountPathPrometheusKafkaAdapter {
	if in == nil {
		return nil
	}
	out := new(VolumeMountPathPrometheusKafkaAdapter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Volumes) DeepCopyInto(out *Volumes) {
	*out = *in
	out.PrometheusConfig = in.PrometheusConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Volumes.
func (in *Volumes) DeepCopy() *Volumes {
	if in == nil {
		return nil
	}
	out := new(Volumes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumesMountPathOrc8rNginx) DeepCopyInto(out *VolumesMountPathOrc8rNginx) {
	*out = *in
	if in.MountPath != nil {
		in, out := &in.MountPath, &out.MountPath
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumesMountPathOrc8rNginx.
func (in *VolumesMountPathOrc8rNginx) DeepCopy() *VolumesMountPathOrc8rNginx {
	if in == nil {
		return nil
	}
	out := new(VolumesMountPathOrc8rNginx)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumesNmsMagmaLte) DeepCopyInto(out *VolumesNmsMagmaLte) {
	*out = *in
	if in.Secretname != nil {
		in, out := &in.Secretname, &out.Secretname
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumesNmsMagmaLte.
func (in *VolumesNmsMagmaLte) DeepCopy() *VolumesNmsMagmaLte {
	if in == nil {
		return nil
	}
	out := new(VolumesNmsMagmaLte)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumesOrc8rNginx) DeepCopyInto(out *VolumesOrc8rNginx) {
	*out = *in
	if in.SecretName != nil {
		in, out := &in.SecretName, &out.SecretName
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumesOrc8rNginx.
func (in *VolumesOrc8rNginx) DeepCopy() *VolumesOrc8rNginx {
	if in == nil {
		return nil
	}
	out := new(VolumesOrc8rNginx)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumesUserGrafana) DeepCopyInto(out *VolumesUserGrafana) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumesUserGrafana.
func (in *VolumesUserGrafana) DeepCopy() *VolumesUserGrafana {
	if in == nil {
		return nil
	}
	out := new(VolumesUserGrafana)
	in.DeepCopyInto(out)
	return out
}
