apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pmnsystem-rolebinding
subjects:
- kind: ServiceAccount
  name: pmn
  namespace: pmn
roleRef:
  kind: ClusterRole
  name: pmnsystem-role 
  apiGroup: rbac.authorization.k8s.io
