apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: aws-efs
    volume.kubernetes.io/storage-provisioner: aws-efs
  creationTimestamp: "2023-06-15T11:23:22Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: promcfg
  namespace: pmn
  resourceVersion: "20205"
  uid: 07260722-fd73-4f78-bbe9-7367d0bf32a3
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  volumeMode: Filesystem
  volumeName: pvc-07260722-fd73-4f78-bbe9-7367d0bf32a3
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  phase: Bound